### ISSUE TITLE
保存文档时一直提示保存失败

### ISSUE THREAD

**Issue by zhangrt** [mindoc-org/mindoc#287]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
0.10.1

2. 你当前使用的是什么操作系统?
客户端 win10 服务端 centos 7.2

3. 你是如何操作的？
正常编辑文档后保存

4. 你期望得到什么结果?
保存成功

5. 当前遇到的是什么结果?
提示：保存失败
errorcode：6006

**Comment by lifei6671** [comment]
看看错误日志里面是什么错误。

**Comment by zhangrt** [comment]
2018/05/28 07:31:49.911 [E] [DocumentController.go:751] InsertOrUpdate =>  Error
 1105: Parameter of prepared statement which is set through mysql_send_long_data
() is longer than 'max_allowed_packet' bytes

之前保存过的内存现在重新编辑点保存也失败。

**Comment by zhangrt** [comment]
@lifei6671 
2018/05/28 07:31:49.911 [E] [DocumentController.go:751] InsertOrUpdate =>  Error
 1105: Parameter of prepared statement which is set through mysql_send_long_data
() is longer than 'max_allowed_packet' bytes

之前保存成功的内容，点击编辑后不作修改，点击保存也报改错。

**Comment by lifei6671** [comment]
应该是你mysql配置有问题，建议你谷歌一下。

**Comment by zhangrt** [comment]
@lifei6671 已解决，多谢
