### ISSUE TITLE
域名备案跳转目标地址需要更新

### ISSUE THREAD

**Issue by liarme** [mindoc-org/mindoc#485]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc current version =>  v2.0
MinDoc last version =>  v2.0

2. 你当前使用的是什么操作系统?
CentOS Linux release 7.6.1810 (Core)

3. 你是如何操作的？
添加域名备案号

4. 你期望得到什么结果?
工信部网站域名已经变更，现在需要更新跳转目标为 http://www.beian.miit.gov.cn/

5. 当前遇到的是什么结果?
现在是跳转到旧的工信部域名

**Comment by xlpppp** [comment]
自行修改 /views/widgets/footer.tpl 就行了
