### ISSUE TITLE
[bug]未加入文章团队的用户RoleId默认是0(创始人)，导致出现编辑按钮，点击之后又无权限

### ISSUE THREAD

**Issue by xiaoqiang** [mindoc-org/mindoc#534]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.0

2. 你当前使用的是什么操作系统?
centos7

3. 你是如何操作的？
普通用户看别人的文章会出现编辑按钮，然而点进去又提示没有权限

4. 你期望得到什么结果?
普通用户看别人文章的时候不出现编辑按钮，打印了一下未加入文章团队的RoleId被默认为0(创始人)了

5. 当前遇到的是什么结果?

**Comment by lifei6671** [comment]
是哪个也没的编辑按钮？

**Comment by xiaoqiang** [comment]
1. 普通用户看别人文章，用户不在文章的用户组里面，打印roleid=0；
2. 文章作者看自己文章，因为是创始人，打印roleId=0；
3.普通用户加入到别人文章的用户组，设置某个角色比如观察者，打印roleid为对应的值，观察者roleid=3；
4. 普通用户从别人文章的用户组里面删除，打印roleid=0，回到了第一种情况。

另外建议，权限不和文章绑定，和空间绑定比较好，团队也和空间绑定。参照https://www.yuque.com/

**Comment by lifei6671** [comment]
因为最早的时候只有文章，没有空间和团队。所以才和文章绑定了。
这个问题我研究下。

**Comment by xiaoqiang** [comment]
空间还是需要权限的，否则大家可以随便发文章到任意空间，后期管理会很混乱，单篇文章权限继承空间权限即可

**Comment by lifei6671** [comment]
你弄错方向了。我这个是针对团队内部用的。你说的这个是 <https://github.com/TruthHun/BookStack> 这个。

**Comment by xiaoqiang** [comment]
我也是团队内部使用，你发的那个太复杂了。。。

**Comment by xiaoqiang** [comment]
权限的问题可以早点fix吗？我本地(OSX)编译一直有点问题
