### ISSUE TITLE
项目已经不维护了吗？

### ISSUE THREAD

**Issue by MetSystem** [mindoc-org/mindoc#592]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by 3xxx** [comment]
可能需要大家共同努力。

**Comment by lifei6671** [comment]
工作频繁变动，没精力开发了。😂

**Comment by gsw945** [comment]
GitHub社区组织 [mindoc-org](https://github.com/mindoc-org) 持续维护中
