### ISSUE TITLE
请问V2.0没有评论管理功能吗？

### ISSUE THREAD

**Issue by Melvon-mao** [mindoc-org/mindoc#615]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
mindoc_linux_amd64.zip

2. 你当前使用的是什么操作系统?
OSX Catalina

4. 你期望得到什么结果?
管理员账号进去能看到评论管理模块，普通用户能对文档进行评论。

5. 当前遇到的是什么结果?
无法看到评论功能。

**Comment by gsw945** [comment]
评论功能已合并到master
