### ISSUE TITLE
使用源码编译安装后，admin登陆一直是非法请求。登陆不成功

### ISSUE THREAD

**Issue by trezhangqiang** [mindoc-org/mindoc#673]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
      
      用的是源码编译安装(git clone https://github.com/mindoc-org/mindoc.git)

2. 你当前使用的是什么操作系统?
      win10

3. 你是如何操作的？
    git下载后，在linux系统中 按照说明 依次执行。
    go mod tidy
    go build -ldflags "-w"
    ./mindoc install
     ./mindoc

4. 你期望得到什么结果?
    执行完step3 以后启动后，可以访问到  http://:8181，但是输入 admin  123456 和验证码后
    一直返回非法请求,登陆不成功。

5. 当前遇到的是什么结果?
    登陆失败

**Comment by roberChen** [comment]
试试把xsrf关掉呢？

**Comment by trezhangqiang** [comment]
恩，可以了。非常感谢。
