### ISSUE TITLE
ifram标签可预览，发布不显示。

### ISSUE THREAD

**Issue by chairman666** [mindoc-org/mindoc#690]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新docker版

2. 你当前使用的是什么操作系统?
Centos 7.6

3. 你是如何操作的？
ifram标签预览正常，发布后空白，不显示。
`<p>
<iframe style="width: 100%; height: 650px;" src="https://ac.yunyoujun.cn" frameborder="0" width="320" height="240"/>
</p>`

4. 你期望得到什么结果?
装上我心爱的小空调~

5. 当前遇到的是什么结果?

**Comment by gsw945** [comment]
处于安全性考虑，iframe标签被屏蔽了，后续考虑允许通过配置文件启用

**Comment by gsw945** [comment]
版本[v2.1-beta.5](https://github.com/mindoc-org/mindoc/releases/tag/v2.1-beta.5) 已新增 `enable_iframe` 配置支持 iframe
