### ISSUE TITLE
加载时区配置信息失败,请检查是否存在 ZONEINFO 环境变量-> unknown time zone Asia/Shanghai

### ISSUE THREAD

**Issue by pingan5200** [mindoc-org/mindoc#695]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
 master

2. 你当前使用的是什么操作系统?
用的master的docker

3. 你是如何操作的？
docker-compose -f docker-compose.yml up 

4. 你期望得到什么结果?
顺利启动

5. 当前遇到的是什么结果?
报错 
![image](https://user-images.githubusercontent.com/46984607/123920238-50ef4500-d9b8-11eb-8153-a394f3a6f6f8.png)

**Comment by gsw945** [comment]
请问是直接使用的master版本的docker-compose.yml吗？如果是，请修改docker-compose.yml中的docker镜像地址，目前Dockerfile更新了，但是docker-compose.yml还没有更新

**Comment by ysq5202121** [comment]
使用管理员运行没毛病

**Comment by gsw945** [comment]
Dockerfile已更新，之前没有安装`tzdata`包，现已修复
