### ISSUE TITLE
redis 初始化连接失败

### ISSUE THREAD

**Issue by DontDream1** [mindoc-org/mindoc#708]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

 docker- v 2 .1.beat.4

2. 你当前使用的是什么操作系统?
linux centos7 

3. 你是如何操作的？
初始化连接redis

4. 你期望得到什么结果?

初始化成功

5. 当前遇到的是什么结果?

`2021/08/03 17:14:20.945 [E] [command.go:420]  初始化Redis缓存失败: ERROR-4002020, could not unmarshal the config: {"conn":"192.168.1.43:6379","password":"123456","dbNum":0}: json: cannot unmarshal number into Go value of type string
`

**Comment by makotome** [comment]
我也遇到同样的情况:
2021/08/04 09:32:09.678 [E] [command.go:420]  初始化Redis缓存失败: ERROR-4002020, could not unmarshal the config: {"conn":"xx.xxx.xx.com:6379","password":"xxxxxxx","dbNum":0}: json: cannot unmarshal number into Go value of type string

系统：centos8.4
版本：MinDoc last version =>  v2.1-beta.1
操作：cache 使用 redis.
#缓存方式:memory/memcache/redis/file
cache_provider="${MINDOC_CACHE_PROVIDER||redis}"
结果：希望可以正常 install 初始化。
