### ISSUE TITLE
上传文件附件不显示

### ISSUE THREAD

**Issue by WVenus** [mindoc-org/mindoc#728]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
我是使用的docker运行的mindoc

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
我上传word文件和excel文件后无法显示

4. 你期望得到什么结果?
上传后的word、excel文件能在md文件中显示出来

5. 当前遇到的是什么结果?

**Comment by Ryan2009** [comment]
我也遇到这个问题
