### ISSUE TITLE
默认账号密码不存在

### ISSUE THREAD

**Issue by qianmianyao** [mindoc-org/mindoc#729]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.1

2. 你当前使用的是什么操作系统?
3. linux

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?
admin 123456
无法登录

**Comment by gsw945** [comment]
`godoc_linux_amd64 install` 是否成功执行了？

**Comment by gonboy** [comment]
同样的问题。 启动后。
用 
root 123456 
admin 123456

无法登录
