### ISSUE TITLE
文档编辑历史记录显示空白

### ISSUE THREAD

**Issue by InGramViking** [mindoc-org/mindoc#736]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.1-beta.1 代码，Dockerfile使用的 master分支552cac7提交的去掉清华源 ，自己构建的镜像

2. 你当前使用的是什么操作系统?
centos7.6

3. 你是如何操作的？
点击进入编辑文章界面，右侧点击历史记录，历史记录弹窗内容空白，后台日志报错

4. 你期望得到什么结果?
历史记录页面内容显示正常

5. 当前遇到的是什么结果?
历史记录弹窗内容空白，后台日志报错

**Comment by gsw945** [comment]
暂时请用master代码，v2.1-beta.1 版本的，i18功能有bug
