### ISSUE TITLE
项目加密后访问页面空白

### ISSUE THREAD

**Issue by M-Artisan** [mindoc-org/mindoc#751]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.1-beta.5

2. 你当前使用的是什么操作系统?
windows10 21H2

3. 你是如何操作的？
项目设为私有，设置密码访问，开启匿名访问

4. 你期望得到什么结果?
未登陆状态下，打开项目页面，输入密码可以访问

5. 当前遇到的是什么结果?
未登陆状态下，打开项目页面显示空白

**Comment by focusos** [comment]
> 临时解决：document_password.tpl 文件 的国际化字段 都改成静态  

是的，我也发现了。
