### ISSUE TITLE
请问想推PR,在哪个分支开发?

### ISSUE THREAD

**Issue by little-nine** [mindoc-org/mindoc#755]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
2.1-beta5

2. 你当前使用的是什么操作系统?
mac

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by gsw945** [comment]
目前直接是在`master`分支，因为参与者少，所以直接是在主分支的
