### ISSUE TITLE
mindoc使用手册链接地址都不能访问

### ISSUE THREAD

**Issue by 7-happy** [mindoc-org/mindoc#756]
1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
使用的阿里云docker镜像 registry.cn-hangzhou.aliyuncs.com/mindoc/mindoc:v2.0-beta.2

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
docker-compose部署成功

4. 你期望得到什么结果?
部署成功只是第一步，接下来比如文档发布、数据迁移等方面的内容，想通过作者github该项目的“mindoc使用手册”查找对应的指导，可是发现该手册所有的链接地址都不能访问。

5. 当前遇到的是什么结果?
mindoc使用手册中的文档链接能正常访问

**Comment by gsw945** [comment]
原作者-站点: https://www.iminho.me/wiki/docs/mindoc  由于cdn过期，导致css和图片等资源访问异常

当前维护-站点: https://doc.gsw945.com/docs/mindoc-docs/ 从原作者站点移植而来。

**Comment by 7-happy** [comment]
好的~ 感谢！
