### ISSUE TITLE
感谢大佬 支持 mermaid！！！

### ISSUE THREAD

**Issue by younglinuxer** [mindoc-org/mindoc#759]
docker版本对mermaid 支持有问题  感谢大佬最新更新的版本已经支持 mermaid
拉下来重新编译就行了！！ 感谢大佬

![image](https://user-images.githubusercontent.com/20791907/147619222-a1221c24-99a0-4646-a68c-e8c079bf5a83.png)

**Comment by xiangcaojc** [comment]
是不是這個
![微信截图_20220106212358](https://user-images.githubusercontent.com/51392780/148389551-7dd44d29-f5a7-4acd-bb2b-6b12bec1f93c.png)
https://wiki.xcao.vip/static/editor.md/lib/mermaid/mermaid.css 這個css文件訪問也不到

**Comment by gsw945** [comment]
Duplicate of #762
