### ISSUE TITLE
最新版本没有看到评论功能

### ISSUE THREAD

**Issue by tomato-cc** [mindoc-org/mindoc#760]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.1-beta.5 

2. 你当前使用的是什么操作系统?
linux

3. 你是如何操作的？
该系统之前部署的是v2.0版本，因为看到新增了评论，就升级了最新版（删除原来项目，备份数据库后也删除了数据库 upload文件夹下因为有之前上传的图片，因此被我替换了）

4. 你期望得到什么结果?
评论功能

5. 当前遇到的是什么结果?
页面看不到评论按钮

**Comment by gsw945** [comment]
评论功能已合并到master
