### ISSUE TITLE
docker版mindoc,mermaid.css显示404

### ISSUE THREAD

**Issue by xiangcaojc** [mindoc-org/mindoc#762]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
docker版mindoc:v2.1-beta.5

2. 你当前使用的是什么操作系统?
centos8

3. 你是如何操作的？
訪問的時候https://wiki.xcao.vip/static/editor.md/lib/mermaid/mermaid.css显示404
并且访问路径报错

4. 你期望得到什么结果?
mermaid.css可以正常加载

5. 当前遇到的是什么结果?
![image](https://user-images.githubusercontent.com/51392780/148393243-019b7094-3feb-4305-b588-c52c6ad95da5.png)

**Comment by gsw945** [comment]
参考 commit [新版 mermaid 不需要css文件，移除不存在的css引用](https://github.com/mindoc-org/mindoc/commit/50888fb1340cb58cc5bbe4eaab212f36f4a0bd87) , 新版本暂未发布，故而未应用此commit修改
