### ISSUE TITLE
站点 css 证书过期了

### ISSUE THREAD

**Issue by thissuper** [mindoc-org/mindoc#764]
https://www.iminho.me/wiki/docs/mindoc 的 css 证书过期了

![image](https://user-images.githubusercontent.com/57950591/149963429-3372c195-1ae9-494a-be2e-2c308ebd6f6d.png)

**Comment by gsw945** [comment]
站点  `www.iminho.me` 归原作者 [Minho](https://github.com/lifei6671)所有，原作者已未参与mindoc维护，请访问目前新站点 `doc.gsw945.com`
