### ISSUE TITLE
无网环境下使用Docker部署，程序启动失败

### ISSUE THREAD

**Issue by lx-svg** [mindoc-org/mindoc#771]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
FROM registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1-beta.5 
2. 你当前使用的是什么操作系统?
Linux
3. 你是如何操作的？
部署基于`registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1-beta.5 ` 镜像的容器
4. 你期望得到什么结果?
程序启动
5. 当前遇到的是什么结果?
运行容器时，容器内部脚本执行下载操作，程序启动失败

- 当我在无网环境下执行时，容器内部脚本 `/mindoc/sync_host.sh` 下载 `rclone` 程序失败导致程序无法启动，是否应该将下载操作全部提至镜像构建时？目前我只能通过重写DockerFile重新构建镜像解决

**Comment by gsw945** [comment]
后续版本，rclone将被去掉，不再依赖公网。

**Comment by lx-svg** [comment]
发现该问题的相关讨论已经在 #737 提出，期待后续的更新
