### ISSUE TITLE
文章密码输入正确无法访问

### ISSUE THREAD

**Issue by kylincodelab** [mindoc-org/mindoc#774]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
[v2.1-beta.5](https://github.com/mindoc-org/mindoc/releases/tag/v2.1-beta.5)

2. 你当前使用的是什么操作系统?

ubuntu 20

3. 你是如何操作的？

文章设置密码后，别人用浏览器输入文章密码，还是无法访问（测试了几台电脑也是一样，自己输入密码访问没问题，别人就不行）

4. 你期望得到什么结果?

文章输入正确密码都能访问

5. 当前遇到的是什么结果?

文章输入正确密码无法 访问

**Comment by Go-Go-Farther** [comment]
这个看代码里面设计就是：私密文章只能作者自己和管理员可以通过密码访问，其他的用户知道密码也不能访问
