### ISSUE TITLE
增加了TOC标签，但是文档导航生成到顶端了

### ISSUE THREAD

**Issue by Angus221** [mindoc-org/mindoc#785]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
docker v0.13.4

2. 你当前使用的是什么操作系统?
Linux Centos7

3. 你是如何操作的？
增加了[TOC]

4. 你期望得到什么结果?

右侧出现列表

5. 当前遇到的是什么结果?

没有出现在右侧，出现在文档顶部了
![image](https://user-images.githubusercontent.com/21039420/160354815-465d5d6c-f76d-4bb8-9a0f-f10e7e793db4.png)

**Comment by gsw945** [comment]
docker v0.13.4是很早的版本了，我对这个版本的不清楚，可以试试最新版本。

**Comment by Angus221** [comment]
好的 升级到最新版好了
