### ISSUE TITLE
docker版本评论功能不可用

### ISSUE THREAD

**Issue by xiangcaojc** [mindoc-org/mindoc#796]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
docker v2.1-beta.6
2. 你当前使用的是什么操作系统?
centos

3. 你是如何操作的？
项目的评论功能

4. 你期望得到什么结果?
评论数据无法加载

5. 当前遇到的是什么结果?
评论功能不可用

**Comment by xiangcaojc** [comment]
![image](https://user-images.githubusercontent.com/51392780/171557638-01661372-7791-4c14-b956-5a2dde3123c6.png)

**Comment by currie0612** [comment]
我使用二进制版本部署也遇到了同样的问题~

你当前使用的是哪个版本的 MinDoc(godoc_linux_amd64 version)?
v2.1-beta.6

你当前使用的是什么操作系统?
ubuntu20.04

你是如何操作的？
项目的评论功能

你期望得到什么结果?
评论数据无法加载

当前遇到的是什么结果?
评论功能不可用

**Comment by gsw945** [comment]
master已修复，未release

**Comment by farerboy** [comment]
那个版本有可用的评论功能呀

**Comment by 3xxx** [comment]
我的咋没评论功能呢？

**Comment by gsw945** [comment]
> 那个版本有可用的评论功能呀

@farerboy 

- release地址: https://github.com/mindoc-org/mindoc/releases/tag/v2.1
- docker镜像: `registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1`

评论报错问题已修复
