### ISSUE TITLE
PC版企业微信用系统浏览器打开

### ISSUE THREAD

**Issue by saozimian** [mindoc-org/mindoc#816]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
最新版
2. 你当前使用的是什么操作系统?
Windows 10 

3. 你是如何操作的？
企业微信打开mindoc

4. 你期望得到什么结果?
调用系统默认浏览器打开，而不是显示在企业微信右侧

5. 当前遇到的是什么结果?
企业微信使用自带浏览器 不能在浏览器中打开

**Comment by gsw945** [comment]
在企业微信内部打开是企业微信的默认行为，mindoc对它来说只是这个url，它会自己打开，如果需要在浏览器中打开，需要点击企业微信里面"用系统浏览器打开"得按钮

**Comment by saozimian** [comment]
新版的企业微信 已经取消该设置，好像需要自己去适配。
