### ISSUE TITLE
文档页无法查看附件信息，找不到任何信息

### ISSUE THREAD

**Issue by Macfee** [mindoc-org/mindoc#850]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

最新版本代码构建的Docker运行环境

2. 你当前使用的是什么操作系统?

Docker 

3. 你是如何操作的？

使用最新的包，全新部署

4. 你期望得到什么结果?

能查看附件

5. 当前遇到的是什么结果?

详情页无法看到附件

**Comment by Mrzhuhanxin** [comment]
@Macfee 需要在详情页中有内容才可以看到附件

**Comment by Macfee** [comment]
详情页面无法看到附件，我下载了最新的源码，编译运行，测试下来也是无法看到附件。

**Comment by Mrzhuhanxin** [comment]
你在详情页必须有内容才能看到,什么都不写是看不到的

**Comment by Go-Go-Farther** [comment]
你这个不能下载附件的问题是不是：
1. 使用的是项目，不是文章；
2. 项目使用的编辑器不是markdown，而是其他的两种；
3. 使用markdown应该是没有问题的。
