### ISSUE TITLE
项目空间列表显示问题

### ISSUE THREAD

**Issue by 312292061** [mindoc-org/mindoc#884]
请按照一下格式提交issue，谢谢！

当前问题：项目空间展示数量不能超过18个

Q：你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
A：registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1

Q：你当前使用的是什么操作系统?
A：WIndsows10

Q：你是如何操作的？
A：添加了超过18个项目空间，但在项目空间列表中只能展示了18个，对于多余的项目空间，没有分页操作可查看

Q：你期望得到什么结果?
A：能展示超过18个项目空间，可通过分页展示

Q：当前遇到的是什么结果?
A：只能显示18个项目空间

PS：查看了代码，发现pageSize定义为18，但看起来应该是有分页操作，不知道是否是bug或是设计如此（本人不大会go lang）
![image](https://github.com/mindoc-org/mindoc/assets/19307026/6fece941-8018-4894-9a68-334803978f40)
另外 ，可以将pageSize定义为20，这样可刚好展示为 4列x5行

**Comment by gsw945** [comment]
#fixed by https://github.com/mindoc-org/mindoc/commit/5011aa964f045a128c0dc1969cc5eccf16a5ac0f
