### ISSUE TITLE
建议： 代码块能够提供“一键复制”功能

### ISSUE THREAD

**Issue by Saltwater-leo** [mindoc-org/mindoc#900]
1. 使用的镜像版本是 mindoc:v2.1

2. 当前使用的是window11操作系统

3. 操作如下：
   查看文档，复制参数示例代码块

5. 期望：
   代码块能够提供“一键复制”功能

7. 现状：
    当前需要通过鼠标滑动代码块到底部，才能复制代码块内容

**Comment by jh244212647** [comment]
https://github.com/mindoc-org/mindoc/tree/21fe4b631a23f3b2ff1ea913b1bb8e34e8b9ddc1 这笔修改已经添加了代码块复制功能

**Comment by jh244212647** [comment]
@gsw945 这个issue可以关掉了

**Comment by Saltwater-leo** [comment]
查找最新镜像，未找到，

举个栗子-当前(公开)镜像(信息页面:&nbsp;https://cr.console.aliyun.com/images/cn-hangzhou/mindoc-org/mindoc/detail&nbsp;, 需要登录阿里云账号才可访问列表)，

1、这个地址是不是不能用了，我登录上去后如下，也搜不到mindoc 的镜像，不知道怎么才能更新
2、使用新的镜像，v2.1版本的数据库文件能正常使用吗？担心数据库接口有改动，影响已有的





简单
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mindoc-org/mindoc"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月18日(星期三) 晚上8:39
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mindoc-org/mindoc] 建议： 代码块能够提供“一键复制”功能 (Issue #900)





 
https://github.com/mindoc-org/mindoc/tree/21fe4b631a23f3b2ff1ea913b1bb8e34e8b9ddc1 这笔修改已经添加了代码块复制功能

**Comment by xiaonet** [comment]
> https://github.com/mindoc-org/mindoc/tree/21fe4b631a23f3b2ff1ea913b1bb8e34e8b9ddc1 这笔修改已经添加了代码块复制功能

现在的新版本用不了复制的功能使用edge和Google浏览器都无法显示复制的按钮
