### ISSUE TITLE
项目空间，没有排序功能吗，如果没有，希望能够添加？

### ISSUE THREAD

**Issue by nianqinianyi** [mindoc-org/mindoc#904]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.1

2. 你当前使用的是什么操作系统?
docker

3. 你是如何操作的？
创建项目空间，编辑项目空间

4. 你期望得到什么结果?
有排序字段，能够对项目空间进行排序

**Comment by Zzhenping** [comment]
可以在首页进行拖动排序了
