### ISSUE TITLE
docker 运行不能连接指定数据库，且更改端口不生效

### ISSUE THREAD

**Issue by XG520** [mindoc-org/mindoc#907]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1

2. 你当前使用的是什么操作系统?
centos7.6

3. 你是如何操作的？
docker run -d --name mindoc --restart always --net host -v /data/mindoc/:/mindoc/:rw -e DB_ADAPTER=mysql -e MYSQL_PORT_3306_TCP_ADDR=localhost -e MYSQL_PORT_3306_TCP_PORT=3306 -e MYSQL_INSTANCE_NAME=mindoc -e MYSQL_USERNAME=root -e MYSQL_PASSWORD=123456 -e HTTP_PORT=8080 -e MINDOC_ENABLE_EXPORT=true registry.cn-hangzhou.aliyuncs.com/mindoc-org/mindoc:v2.1

4. 你期望得到什么结果?
使用自己部署的数据库，自定义端口为8080，数据持久化

5. 当前遇到的是什么结果?
连不上数据库，容器依然正常运行，重建容器后项目丢失，且端口更改后不生效

**Comment by gsw945** [comment]
1. `VOLUME` 映射请参照 Dockerfile, 不要`/mindoc`整体映射
> https://github.com/mindoc-org/mindoc/blob/18b6ead94d6fd48350d59e1ec2c48c2d73a20b90/Dockerfile#L124

2. 指定端口用环境变量 `MINDOC_PORT`， 参见
> https://github.com/mindoc-org/mindoc/blob/18b6ead94d6fd48350d59e1ec2c48c2d73a20b90/conf/app.conf.example#L5
3. 数据库配置环境变量缺少前缀 `MINDOC_`, 参见
> https://github.com/mindoc-org/mindoc/blob/18b6ead94d6fd48350d59e1ec2c48c2d73a20b90/conf/app.conf.example#L54-L60

**Comment by XG520** [comment]
明白了，变量名问题
