### ISSUE TITLE
导出csv文件，csvExportParams.setSpiltMark()；修改默认的分隔符不生效，最后还是以逗号作为分割符

### ISSUE THREAD

**Issue by zyf1192306713** [mindoc-org/mindoc#910]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

2. 你当前使用的是什么操作系统?

3. 你是如何操作的？

4. 你期望得到什么结果?

5. 当前遇到的是什么结果?

**Comment by gsw945** [comment]
是否问错了地方?
