### ISSUE TITLE
哪位好心人导一份数据库表结构给我

### ISSUE THREAD

**Issue by saysj** [mindoc-org/mindoc#922]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
v2.1
[mindoc_windows_386.7z](https://github.com/mindoc-org/mindoc/releases/download/v2.1/mindoc_windows_386.7z)

2. 你当前使用的是什么操作系统?
Windows server 2008 R2 Enterprise
MySQL8.0.34

3. 你是如何操作的？
手动执行mindoc_windows_386.exe文件

4. 你期望得到什么结果?
完成数据库初始化

5. 当前遇到的是什么结果?
![WechatIMG1037](https://github.com/mindoc-org/mindoc/assets/155125655/65f50305-5663-46d9-9c75-22c4810d33f6)
![Uploading WechatIMG1037.jpg…]()

数据库mindoc_db表是空的。

**Comment by gsw945** [comment]
执行 `mindoc_windows_386.exe install`，会自动初始化表结构，并创建默认超管账户`admin`
