### ISSUE TITLE
请教如何显示锚链接

### ISSUE THREAD

**Issue by jack361** [mindoc-org/mindoc#935]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
查看版本命令返回是空的

2. 你当前使用的是什么操作系统?
Ubuntu20.4

3. 你是如何操作的？

请教下如何加右侧锚链接

4. 你期望得到什么结果?
实现帮助手册的效果
![image](https://github.com/mindoc-org/mindoc/assets/37525249/9693088c-0777-41d8-97bc-ab0452b75062)

5. 当前遇到的是什么结果?
我自己写的文章没有右侧锚链接
![QQ图片20240327011815](https://github.com/mindoc-org/mindoc/assets/37525249/4f6949b6-f677-4acb-96f0-d7175c9fa012)

**Comment by gsw945** [comment]
文档[MinDoc 实现文档导航菜单](https://doc.gsw945.com/docs/mindoc-docs/mindoc-jump.md)
