### ISSUE TITLE
编辑里可以添加字体的编辑和颜色修改吗

### ISSUE THREAD

**Issue by oaleizz** [mindoc-org/mindoc#938]
![image](https://github.com/mindoc-org/mindoc/assets/148640517/45307bbf-4ddc-47ea-8666-1d33302dcdf9)
如图编辑文档的时候需要修改字体大小和颜色，但是上面没有得自己添加对应的代码，希望可以加上相应功能么，或者提点下怎么加上我自己试试~^_^

**Comment by gsw945** [comment]
mindoc中，markdown支持使用html代码，通过修改css样式，比如:
```
<span style="color:#fa1">text with color `#fa1`</span>

<span style="font-size: 30px; font-family: '华文行楷'">font with 大小 `30px`</span>
```
效果如下
![image](https://github.com/mindoc-org/mindoc/assets/6281968/059e5b08-64b2-4892-9fcb-b1e772e401cd)
