### ISSUE TITLE
类似页面是怎么写的呢

### ISSUE THREAD

**Issue by zzfree2021** [mindoc-org/mindoc#949]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?

amd64
2. 你当前使用的是什么操作系统?

centos
3. 你是如何操作的？

4. 你期望得到什么结果?
https://www.iminho.me/wiki/docs/mindoc/mindoc-summary.md，右侧那种结构，点击文字跳到页面的对应位置

5. 当前遇到的是什么结果?

**Comment by gsw945** [comment]
请搜索引擎搜索 Markdown TOC
