### ISSUE TITLE
mindoc运行目录拷贝到新电脑并初始化数据库后，如何恢复已有项目文件

### ISSUE THREAD

**Issue by xtpyutg** [mindoc-org/mindoc#951]
请按照一下格式提交issue，谢谢！

1. 你当前使用的是哪个版本的 MinDoc(`godoc_linux_amd64 version`)?
MinDoc last version =>  v2.2-beta.1

2. 你当前使用的是什么操作系统?
Windows 10 专业版64位

3. 你是如何操作的？
mindoc运行目录拷贝到新电脑并初始化数据库

4. 你期望得到什么结果?
如何恢复已有项目文件

5. 当前遇到的是什么结果?
当前admin账号中“我的项目”只有“MinDoc演示项目”，“我的文章”页面也为空。

**Comment by gsw945** [comment]
用的什么数据库?

**Comment by gsw945** [comment]
如果是sqlite，整体目录打包，解压后，
看到你换了操作系统类型，只需要替换为同版本的可执行文件即可，如果是mysql，请确保conf/app.conf正确

**Comment by xtpyutg** [comment]
是sqlite3，我使用导出导入功能进行恢复了，谢谢

**Comment by gsw945** [comment]
不客气
